### ISSUE TITLE
Not able to load PDF file

### ISSUE THREAD

**Issue by KaushalNirala** [bmurmann/Book-on-MOS-stages#3]
I am not able to download PDF file. Error is "No secure connection". 
If I click on PDF file - then it says -"not able to render" - 'invalid PDF file'.
I would appreciate any help.
Regards

**Comment by bmurmann** [comment]
Are you behind a corporate firewall? People at companies have reported such issues, but these have nothing to do with this repository. Please try with a different internet connection; the PDF download is working as expected.

**Comment by bmurmann** [comment]
Download works as expected.
