### ISSUE TITLE
Possible copy/paste error

### ISSUE THREAD

**Issue by mik1234mc** [bmurmann/Book-on-MOS-stages#4]
Dear Mr. Murmann,

thank you for the great book released in public. During reading, I came across the page 92 and I think that one expression there is misplaced. As seen in below screenshot (right-bottom), I would expect that instead of `g_{mb} = ...`, there should be an expression for `V_S`, but may be I missed something.

![image](https://user-images.githubusercontent.com/24656413/219462515-1e209ebe-003e-41aa-a357-5e5cf0c557ef.png)

**Comment by bmurmann** [comment]
Yes, this is already captured on the errata page. Please have a look to confirm.
